version: "3.9"

services:
  app:
    container_name: interview_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/interview_db?schema=public
    restart: unless-stopped

  postgres:
    container_name: postgres-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
